### ISSUE TITLE
How to pass value to <plasmid> and refresh the div

### ISSUE THREAD

**Issue by a50604021** [vixis/angularplasmid#4]
Hi,
I put a div in my page and I want to dynamicly create this plasmid part, based on the value input on the page, I want to rebuild the div content and refresh. But when I replace the content, it doesn't work. Do I need to use some method to recompile it?
I tried copy the rebuilt content directly and paste it in the page and after refresh the page, I actually see the picture. 
Can you help me with that?

Many thanks
Shirley

**Comment by rchawdry** [comment]
Could you provide some details on the technology you are using to make the page dynamic (i.e. backend via PHP, front-end using plain Javascript, etc?)  In general, AngularPlasmid uses the AngularJS framework for programmability.  If you're not familiar with this, I can help you through it since it may make things a little easier.

For instance, if you wanted to "bind" a user input to something in AngularPlasmid, let's say the radius of a <plasmidtrack> element, you can declare a form's input tag with a property that can be used by the <plasmidtrack> element. Ex.

<input id="r1" ng-model="myrad">
... (some more markup)..
<plasmid>
   <plasmidtrack radius="{{myrad}}">
</plasmid>
..

This is probably simplistic for your needs, so if you can provide some specifics of what you're using today (i.e. JQuery ), I can provide a better answer.

Thanks!

**Comment by a50604021** [comment]
Hi,

Thank you for your response.
I'm using jQuery to replace the content.
My purpose is to use user input 5' RE , 3' RE , insert, and vector sequence to construct the view for final product. 
$('#SequencePreviewPanel')
                        .append($("<plasmid id='Plasmid'></plasmid>")
                            .attr('sequencelength', (vec5rePart.length + seq.length + vec3rePart.length))
                            .append($("<plasmidtrack id='PlasmidTrack'></plasmidtrack>")
                                .append("<trackscale class='sminor' interval='10'></trackscale><trackscale class='smajor' interval='50' showlabels='1' labelclass='sml'></trackscale><trackscale class='smajorin' interval='50' direction='in'></trackscale>")
                                .append($("<trackmarker></trackmarker>")
                                .attr("class","marker")
                                .attr("start", (index5RE + re5seq.length))
                                .attr("end", (index3RE - 1))
                                .append($('<markerlabel></markerlabel>')
                                        .attr("class", "mlabel")
                                        .attr("vadjust",-40)
                                        .attr("text", (seqNameID.val() != "" ? seqNameID.val() : ""))))))
Thanks again.

**Comment by rchawdry** [comment]
Were there some markup elements in your `append` calls?  In GitHub, these are showing up as empty strings.  Would you be able to escape them with the backtick '`' so that these show up in the code?

**Comment by a50604021** [comment]
Just Updated it. Thanks.

**Comment by rchawdry** [comment]
There are a couple of ways to do this.  First,the "right" way is to use the AngularJS framework to manipulate and interact with the plasmid.  If you'd like programmatic control, AngularJS has dedicated, structured programming blocks that are organized into a model-view-controller (MVC) mechanisms.  I'll can put something in JSFiddle that shows how to do this.

The "quick and dirty" approach that takes your jQuery calls and "recompiles" Angular can be done as well.  Essentially, after your jQuery calls, you can add the following:

`recompile('#SequencePreviewPanel');

function recompile(elem){
        angular.element(document).injector().invoke(function($compile){
                var angElem = angular.element(elem);
                $compile(angElem)(angElem.scope());
        });
}`

**Comment by rchawdry** [comment]
OK. I just created a sample on CodePen at http://codepen.io/anon/pen/bNOdoQ

Some background:

HTML
```html
<div id='SequencePreviewPanel' ng-controller='Main'>
  <plasmid>
    <plasmidtrack id="t1" radius="{{radius}}">
      <tracklabel text="Size : {{radius}}"></tracklabel>
    </plasmidtrack>
  </plasmid>
  <button ng-click='addRadius()'>Bigger</button>
  <button ng-click='removeRadius()'>Smaller</button>
</div>
```
JS
```javascript
angular.module('app').controller('Main',function($scope){
	$scope.radius = 50;
  
  $scope.addRadius = function(){
    $scope.radius += 10;
  }
  
  $scope.removeRadius = function(){
    $scope.radius -= 10;
  }
  
})
```

**Comment by a50604021** [comment]
This one works.Thank you so much for your help.
